package max.utility.tomato.gui;

import max.utility.tomato.Countdown;
import max.utility.tomato.dao.TomatoDaoImpl;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class StartTimer extends javax.swing.JFrame {

	/**
	 * 
	 */
	private static final long serialVersionUID = 4105760033118242900L;

	public static final Logger logger = LoggerFactory.getLogger(StartTimer.class);

	private TomatoDaoImpl tomatoDao;

	/**
	 * Creates new form StartTimer
	 */
	public StartTimer() {
		initComponents();
	}

	public StartTimer(TomatoDaoImpl tomatoDao) {
		this.tomatoDao = tomatoDao;
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {
		this.setTitle("start timer");

		lbl_focusOn = new javax.swing.JLabel();
		jScrollPane1 = new javax.swing.JScrollPane();
		ta_focusOn = new javax.swing.JTextArea();
		btnStartTomato = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		lbl_focusOn.setLabelFor(ta_focusOn);
		lbl_focusOn.setText("Focus");

		ta_focusOn.setColumns(20);
		ta_focusOn.setRows(5);
		ta_focusOn.setTabSize(2);
		ta_focusOn.setForeground(new java.awt.Color(0, 153, 0));
		ta_focusOn
				.setText("descrivi cosa intendi fare nei prossimi 20 minuti...\n[Ctrl+tab] per togliere il \"focus\" dall' area di testo");
		ta_focusOn
				.setToolTipText("descrivi cosa intendi fare nei prossimi 20 minuti... \n[Ctrl+tab] per togliere il \"focus\" dall' area di testo");
		jScrollPane1.setViewportView(ta_focusOn);
		ta_focusOn.getAccessibleContext().setAccessibleName("ta_focusOn");

		btnStartTomato.setText("inizia");
		btnStartTomato.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				btnStartTomatoMouseClicked(evt);
			}
		});
		btnStartTomato.addKeyListener(new java.awt.event.KeyAdapter() {
			public void keyPressed(java.awt.event.KeyEvent evt) {
				btnStartTomatoKeyPressed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				layout.createSequentialGroup()
						.addContainerGap()
						.addGroup(
								layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 380,
												Short.MAX_VALUE)
										.addGroup(
												layout.createSequentialGroup()
														.addGroup(
																layout.createParallelGroup(
																		javax.swing.GroupLayout.Alignment.LEADING)
																		.addComponent(lbl_focusOn,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				36,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addComponent(btnStartTomato))
														.addGap(0, 0, Short.MAX_VALUE))).addContainerGap()));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				layout.createSequentialGroup()
						.addGap(31, 31, 31)
						.addComponent(lbl_focusOn)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 134,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(btnStartTomato).addContainerGap(86, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>

	private void btnStartTomatoMouseClicked(java.awt.event.MouseEvent evt) {
		saveTomato(ta_focusOn.getText());
	}

	private void btnStartTomatoKeyPressed(java.awt.event.KeyEvent evt) {
		System.out.println("btnStartTomatoKeyPressed");
	}

	void saveTomato(String focusOn) {
		logger.debug("save tomato");
		// tomatoDao.save(new Tomato(focusOn));
		// WindowEvent wev = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
		// Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(wev);
		setVisible(false);
		dispose();
		countDown();
	}

	private void countDown() {
		Countdown beeperControl = new Countdown(this);
		beeperControl.start();
	}

	public void openWindow() {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed"
		// desc=" Look and feel setting code (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the
		 * default look and feel. For details see
		 * http://download.oracle.com/javase
		 * /tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (Exception ex) {
			logger.error(null, ex);
		}
		// </editor-fold>

		/* Create and display the form */
		// java.awt.EventQueue.invokeLater(new Runnable() {
		// public void run() {
		// new StartTimer().setVisible(true);
		// }
		// });
	}

	// Variables declaration - do not modify
	private javax.swing.JButton btnStartTomato;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JLabel lbl_focusOn;
	private javax.swing.JTextArea ta_focusOn;
	// End of variables declaration
}