/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package tomatogui;

/**
 * 
 * @author MAX
 */
public class EndTimer extends javax.swing.JFrame {

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed"
		// desc=" Look and feel setting code (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the
		 * default look and feel. For details see
		 * http://download.oracle.com/javase
		 * /tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(EndTimer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(EndTimer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(EndTimer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(EndTimer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new EndTimer().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify
	private javax.swing.JButton btn_reviewCompleted;

	private javax.swing.JButton jButton1;

	private javax.swing.JScrollPane jScrollPane1;

	private javax.swing.JScrollPane jScrollPane3;

	private javax.swing.JScrollPane jScrollPane4;
	private javax.swing.JLabel lbl_focusOn;
	private javax.swing.JLabel lbl_problemsRaised;
	private javax.swing.JLabel lbl_reallyDone;
	private javax.swing.JLabel lbl_review;
	private javax.swing.JTextArea ta_problemsRaised;
	private javax.swing.JTextArea ta_reallyDone;
	private javax.swing.JTextArea ta_reallyDone1;

	// End of variables declaration
	/**
	 * Creates new form EndTomato
	 */
	public EndTimer() {
		initComponents();
	}

	private void btn_reviewCompletedActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void btn_reviewCompletedKeyPressed(java.awt.event.KeyEvent evt) {
		// TODO add your handling code here:
	}

	private void btn_reviewCompletedMouseClicked(java.awt.event.MouseEvent evt) {
		// TODO add your handling code here:
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		lbl_review = new javax.swing.JLabel();
		lbl_focusOn = new javax.swing.JLabel();
		lbl_reallyDone = new javax.swing.JLabel();
		jScrollPane1 = new javax.swing.JScrollPane();
		ta_reallyDone = new javax.swing.JTextArea();
		lbl_problemsRaised = new javax.swing.JLabel();
		jScrollPane3 = new javax.swing.JScrollPane();
		ta_problemsRaised = new javax.swing.JTextArea();
		jScrollPane4 = new javax.swing.JScrollPane();
		ta_reallyDone1 = new javax.swing.JTextArea();
		jButton1 = new javax.swing.JButton();
		btn_reviewCompleted = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setBackground(new java.awt.Color(0, 0, 0));

		lbl_review.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
		lbl_review.setForeground(new java.awt.Color(255, 153, 0));
		lbl_review.setText("rivedi quanto fatto");

		lbl_focusOn.setBackground(new java.awt.Color(0, 0, 0));
		lbl_focusOn.setForeground(new java.awt.Color(0, 204, 204));
		lbl_focusOn.setText("volevo fare ...");

		lbl_reallyDone.setForeground(new java.awt.Color(0, 0, 255));
		lbl_reallyDone.setLabelFor(ta_reallyDone);
		lbl_reallyDone.setText("ho fatto");

		ta_reallyDone.setEditable(false);
		ta_reallyDone.setBackground(new java.awt.Color(0, 0, 0));
		ta_reallyDone.setColumns(20);
		ta_reallyDone.setFont(new java.awt.Font("Andalus", 0, 13)); // NOI18N
		ta_reallyDone.setForeground(new java.awt.Color(0, 255, 255));
		ta_reallyDone.setRows(10);
		ta_reallyDone.setTabSize(2);
		ta_reallyDone
				.setText("finestre di start e stop (versione base) ok\nformattazione del codice ok\neseguire il codice da riga di comando ok\navvio e stop del timer ok\n");
		ta_reallyDone.setToolTipText("breve revisione di quanto fatto ..");
		ta_reallyDone.setMargin(new java.awt.Insets(0, 2, 2, 2));
		jScrollPane1.setViewportView(ta_reallyDone);

		lbl_problemsRaised.setForeground(new java.awt.Color(204, 0, 0));
		lbl_problemsRaised.setLabelFor(ta_problemsRaised);
		lbl_problemsRaised.setText("difficoltà, impedimenti, problemi, ...");

		jScrollPane3.setBackground(new java.awt.Color(204, 0, 0));

		ta_problemsRaised.setColumns(20);
		ta_problemsRaised.setFont(new java.awt.Font("Andalus", 0, 13)); // NOI18N
		ta_problemsRaised.setForeground(new java.awt.Color(204, 0, 0));
		ta_problemsRaised.setRows(10);
		ta_problemsRaised.setTabSize(2);
		ta_problemsRaised
				.setText("finestre di start e stop (versione base) ok\nformattazione del codice ok\neseguire il codice da riga di comando ok\navvio e stop del timer ok\n");
		ta_problemsRaised.setToolTipText("breve revisione di quanto fatto ..");
		ta_problemsRaised.setMargin(new java.awt.Insets(0, 2, 2, 2));
		jScrollPane3.setViewportView(ta_problemsRaised);

		ta_reallyDone1.setColumns(20);
		ta_reallyDone1.setFont(new java.awt.Font("Andalus", 0, 13)); // NOI18N
		ta_reallyDone1.setForeground(new java.awt.Color(0, 0, 255));
		ta_reallyDone1.setRows(10);
		ta_reallyDone1.setTabSize(2);
		ta_reallyDone1.setText("salva le ultime modifiche.\ncommit -m \"fine timer\"\n");
		ta_reallyDone1.setToolTipText("breve revisione di quanto fatto ..");
		ta_reallyDone1.setMargin(new java.awt.Insets(0, 2, 2, 2));
		jScrollPane4.setViewportView(ta_reallyDone1);

		jButton1.setText("jButton1");

		btn_reviewCompleted.setText("ok");
		btn_reviewCompleted.addMouseListener(new java.awt.event.MouseAdapter() {
			@Override
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				btn_reviewCompletedMouseClicked(evt);
			}
		});
		btn_reviewCompleted.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btn_reviewCompletedActionPerformed(evt);
			}
		});
		btn_reviewCompleted.addKeyListener(new java.awt.event.KeyAdapter() {
			@Override
			public void keyPressed(java.awt.event.KeyEvent evt) {
				btn_reviewCompletedKeyPressed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGroup(
										layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														javax.swing.GroupLayout.Alignment.TRAILING,
														layout.createSequentialGroup()
																.addGap(0, 0, Short.MAX_VALUE)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING)
																				.addComponent(
																						jScrollPane4,
																						javax.swing.GroupLayout.Alignment.TRAILING,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						500,
																						javax.swing.GroupLayout.PREFERRED_SIZE)
																				.addComponent(
																						jScrollPane3,
																						javax.swing.GroupLayout.Alignment.TRAILING,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						500,
																						javax.swing.GroupLayout.PREFERRED_SIZE)))
												.addGroup(
														layout.createSequentialGroup()
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING)
																				.addGroup(
																						layout.createSequentialGroup()
																								.addGap(20, 20, 20)
																								.addComponent(
																										lbl_reallyDone))
																				.addGroup(
																						layout.createSequentialGroup()
																								.addGap(20, 20, 20)
																								.addComponent(
																										lbl_problemsRaised))
																				.addGroup(
																						layout.createSequentialGroup()
																								.addGap(359, 359, 359)
																								.addComponent(jButton1))
																				.addGroup(
																						layout.createSequentialGroup()
																								.addGap(19, 19, 19)
																								.addGroup(
																										layout.createParallelGroup(
																												javax.swing.GroupLayout.Alignment.LEADING)
																												.addComponent(
																														jScrollPane1,
																														javax.swing.GroupLayout.PREFERRED_SIZE,
																														500,
																														javax.swing.GroupLayout.PREFERRED_SIZE)
																												.addGroup(
																														layout.createSequentialGroup()
																																.addComponent(
																																		lbl_focusOn,
																																		javax.swing.GroupLayout.PREFERRED_SIZE,
																																		79,
																																		javax.swing.GroupLayout.PREFERRED_SIZE)
																																.addGap(92,
																																		92,
																																		92)
																																.addComponent(
																																		lbl_review)))))
																.addGap(0, 0, Short.MAX_VALUE))).addContainerGap())
				.addGroup(
						layout.createSequentialGroup().addGap(237, 237, 237).addComponent(btn_reviewCompleted)
								.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				layout.createSequentialGroup()
						.addContainerGap()
						.addGroup(
								layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addGroup(
												layout.createSequentialGroup().addComponent(lbl_review)
														.addGap(15, 15, 15))
										.addGroup(
												javax.swing.GroupLayout.Alignment.TRAILING,
												layout.createSequentialGroup()
														.addComponent(lbl_focusOn)
														.addPreferredGap(
																javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
						.addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 111,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(19, 19, 19)
						.addComponent(lbl_reallyDone)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 111,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(33, 33, 33)
						.addComponent(lbl_problemsRaised)
						.addGroup(
								layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addGroup(
												layout.createSequentialGroup()
														.addGap(1, 1, 1)
														.addComponent(jScrollPane3,
																javax.swing.GroupLayout.PREFERRED_SIZE, 111,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGroup(
												layout.createSequentialGroup()
														.addPreferredGap(
																javax.swing.LayoutStyle.ComponentPlacement.RELATED)
														.addComponent(jButton1))).addGap(18, 18, 18)
						.addComponent(btn_reviewCompleted).addContainerGap(27, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>
}
